server:
  port: 8586
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      routes:
        - id: SubjectService
          uri: http://localhost:8088
          predicates:
            - Path=/api/subject/**
        - id: PracticeService
          uri: http://locahost:9191
          predicates:
            - Path=/api/practice/**
  main:
    web-application-type: reactive


